language: c
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libc6-dev gcc-multilib
script: "( while true; do echo Still going, Travis... >&2; sleep 300; done ) & sudo utils/test-stages.sh"

